[package]
name = "sms-client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["json"] }
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
log = "0.4.28"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
url = "2.5.7"
futures-util = "0.3.31"
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
http = "1.3.1"
